# Generated by Django 5.2.6 on 2025-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_contactmessage_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default='No message provided'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
